--[[

RunTests

Executes all test suites and exits with appropriate status code.

--]]

local Testable = require("@devpackages/testable")
local process = require("@lune/process")

local TESTS = {
    { Name = "ExampleTest", Func = require("../Tests/ExampleTest.spec") },
}

local function runTests()
    local _, passed = Testable.run(TESTS)
    process.exit(if passed then 0 else 1)
end

runTests()
